__default__:
    time: 1-00:00:00
    job-name: CRISPRroots
    ntasks: 1
    cpus-per-task: 4
    mem-per-cpu: 4000
    partition: fastlane 
    output: ./cluster_logs/{rule}_{wildcards}.out
    error: ./cluster_logs/{rule}_{wildcards}.err

CUTADAPT_cleaning:
    job-name: Cutadapt
    cpus-per-task: 6
    mem-per-cpu: 4000
    partition: fastlane

BBDUK_filter_rrna:
    job-name: BBduck
    cpus-per-task: 6
    mem-per-cpu: 4000
    partition: fastlane

STAR_align2pass:
    job-name: STAR
    cpus-per-task: 10
    mem-per-cpu: 4000
    partition: fastlane

PICARD_sortaligned:
    job-name: Picard
    cpus-per-task: 6
    mem-per-cpu: 4000
    partition: fastlane

GATK_markdup:
    job-name: GATK_markdup
    cpus-per-task: 12
    mem-per-cpu: 4000
    partition: fastlane

GATK_splitncigar:
    job-name: GATK_splitcigar
    cpus-per-task: 12
    mem-per-cpu: 4000
    partition: fastlane

GATK_haplotypecaller:
    job-name: HaplotypeCaller
    cpus-per-task: 12
    mem-per-cpu: 4000
    partition: fastlane

BEDTOOLS_intersect_variants_genes:
    job-name: BEDtools_intersect
    cpus-per-task: 12
    mem-per-cpu: 4000
    partition: fastlane

RIsearch2_indexing:
    job-name: RIsearch_indexing
    cpus-per-task: 16
    mem: 60G
    partition: fastlane

RIsearch2_search:
    job-name: RIsearch_search
    cpus-per-task: 16
    mem: 60G
    partition: fastlane

CRISPRoff:
    job-name: CRISPRoff
    cpus-per-task: 16
    mem: 12G
    partition: fastlane

GATK_mutect2_chromosome_wise:
    job-name: MUTECT2
    cpus-per-task: 16
    mem-per-cpu: 4000
    partition: fastlane
    time: 0

FEATURECOUNTS_quantification:
    job-name: FeatureCounts
    cpus-per-task: 4
    mem-per-cpu: 4000
    partition: fastlane

SAMTOOLS_flag:
    job-name: Samtools_flag
    cpus-per-task: 12
    mem-per-cpu: 4000
    partition: fastlane
